services:
  bmlt:
    build:
      context: ..
      dockerfile: docker/Dockerfile-debug
      pull: true
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2}
    ports:
      - "8000:8000"
    environment:
      APP_DEBUG: "true"
      DB_HOST: db
      DB_DATABASE: rootserver
      DB_USERNAME: rootserver
      DB_PASSWORD: rootserver
      DB_PREFIX: na
    depends_on:
      - db
    volumes:
      - ../src:/var/www/html/main_server/
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootserver
      MARIADB_DATABASE: rootserver
      MARIADB_USER: rootserver
      MARIADB_PASSWORD: rootserver
